name: carla
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pip
  - jaxlib
  - jax
  - cuda-nvcc=12.0
  - pip:
    - numpy==1.21.6
    - carla==0.9.13
    - dotmap
    - gym[box2d]
    - flax
    - jax-resnet
    - networkx
    - stable-baselines3
    - tensorboard
    - tensorflow-probability
    - tqdm
    - types-tqdm
    - typing-extensions
